version: 0.4.0
commit: 'chore: bump to v%.%.%'
files:
  README.md:
    - twd v%.%.%
    - 'https://deno.land/x/twd@v%.%.%/cli.ts'
    - 'https://deno.land/x/twd@v%.%.%/types.ts'
    - 'https://deno.land/x/twd@v%.%.%/colors.ts'
  cli.ts:
    - const VERSION = "%.%.%";
    - 'https://deno.land/x/twd@v%.%.%/types.ts'
  cli_test.ts: 'https://deno.land/x/twd@v%.%.%/colors.ts'
