version: 0.2.3
commit: 'chore: bump to v%.%.%'
files:
  README.md:
    - twd v%.%.%
    - 'https://deno.land/x/twd@v%.%.%/cli.ts'
    - 'https://deno.land/x/twd@v%.%.%/types.ts'
  cli.ts:
    - const VERSION = "%.%.%";
    - '"https://deno.land/x/twd@v%.%.%/types.ts";'
